##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=mypass
MODULE_LOAD=1
LIBRARYNAME=mypass

include $(LEVEL)/Makefile.common
